# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bcs_provider_sdk._generated import provider_demo_pb2 as bcs__provider__sdk_dot___generated_dot_provider__demo__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bcs_provider_sdk/_generated/provider_demo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProviderDemoStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/bcs.provider.demo.v1.ProviderDemo/Invoke',
                request_serializer=bcs__provider__sdk_dot___generated_dot_provider__demo__pb2.InvokeRequest.SerializeToString,
                response_deserializer=bcs__provider__sdk_dot___generated_dot_provider__demo__pb2.InvokeResponse.FromString,
                _registered_method=True)


class ProviderDemoServicer:
    """Missing associated documentation comment in .proto file."""

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderDemoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=bcs__provider__sdk_dot___generated_dot_provider__demo__pb2.InvokeRequest.FromString,
                    response_serializer=bcs__provider__sdk_dot___generated_dot_provider__demo__pb2.InvokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bcs.provider.demo.v1.ProviderDemo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bcs.provider.demo.v1.ProviderDemo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProviderDemo:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bcs.provider.demo.v1.ProviderDemo/Invoke',
            bcs__provider__sdk_dot___generated_dot_provider__demo__pb2.InvokeRequest.SerializeToString,
            bcs__provider__sdk_dot___generated_dot_provider__demo__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
