# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bcs_provider_sdk/_generated/provider_demo.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'bcs_provider_sdk/_generated/provider_demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/bcs_provider_sdk/_generated/provider_demo.proto\x12\x14\x62\x63s.provider.demo.v1\" \n\rInvokeRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"9\n\x0eInvokeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x16\n\x0eimplementation\x18\x02 \x01(\t2c\n\x0cProviderDemo\x12S\n\x06Invoke\x12#.bcs.provider.demo.v1.InvokeRequest\x1a$.bcs.provider.demo.v1.InvokeResponseB7\n com.avernet.bcs.provider.demo.v1B\x11ProviderDemoProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bcs_provider_sdk._generated.provider_demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.avernet.bcs.provider.demo.v1B\021ProviderDemoProtoP\001'
  _globals['_INVOKEREQUEST']._serialized_start=73
  _globals['_INVOKEREQUEST']._serialized_end=105
  _globals['_INVOKERESPONSE']._serialized_start=107
  _globals['_INVOKERESPONSE']._serialized_end=164
  _globals['_PROVIDERDEMO']._serialized_start=166
  _globals['_PROVIDERDEMO']._serialized_end=265
# @@protoc_insertion_point(module_scope)
