[package]
name = "bcs-organization-store"
description = "Organization persistence stores for BCS"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
bcs-db-api = { workspace = true }
bcs-domain = { workspace = true }
bcs-service-api = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
bcs-db-local = { workspace = true }
bcs-test-support = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }

[lints]
workspace = true
